config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :studies do
    resources :records do
    end
    resources :participants do
    end
  end

  resources :records do
    resources :participants do
      resources :responses, shallow: true
    end
  end

  root 'static#welcome'

  get 'success' => 'static#success'
end

app/models/participant.rb
require 'valid_email'

class Participant < ActiveRecord::Base
  has_many :responses
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates :email, :presence => true, :email => true
  validates_presence_of :phone
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :study
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :participant
  belongs_to :record
end

app/models/study.rb
require 'csv'

class Study < ActiveRecord::Base
  belongs_to :user
  has_many :records
  has_many :participants

  scope :owned_by, ->(user) { where user_id: user.id }

  def to_csv
    CSV.generate do |csv|
      csv << ['Time', 'Participant ID', 'Who are you with?', 'What are you doing?', 'Pleasure Rating', 'Purpose Rating']
      self.records.each do |record|
        row = []
        record.responses.each do |response|
          row << response.created_at
          row << response.participant_id
          row << response.who
          row << response.what
          row << response.pleasure
          row << response.purpose
        end
        csv << row
      end
    end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :study
  has_many :responses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :studies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

    def after_sign_in_path_for(user)
      studies_path
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_study

  def index
  end

  def new
    @participant = Participant.new
  end

  def create
    @participant = @study.participants.new(participant_params)

    if @study.save
      ParticipantMailer.intro_email(@participant, @study).deliver
      redirect_to study_path(@study)
    else
      flash[:notice] = 'Sorry, something went wrong. Please make sure all required fields are filled out.'
      redirect_to new_study_participant_path
    end
  end

  def destroy
    participant = Participant.find(params[:id])
    participant.destroy
    flash[:notice] = 'Participant successfully removed.'
    redirect_to study_participants_path(@study)
  end

  protected

  def set_study
    @study = Study.find(params[:study_id])
  end

  def participant_params
    params.require(:participant).permit(:first_name, :last_name, :email, :phone, :notes)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_study
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.csv { send_data @study.to_csv }
    end
  end

  def new
    if @study.participants.empty?
      flash[:notice] = 'You must add some participants first!'
      redirect_to new_study_participant_path
    end
    @record = Record.new
  end

  def create
    @record = @study.records.create(record_params)

    if @record.save
      @study.participants.each do |participant|
        RecordMailer.response_email(@study, @record, participant).deliver
      end
      redirect_to study_records_path(@study)
    else
      redirect_to new_study_record_path(@study)
    end
  end

  def show
    @record = Record.find(params[:id])
    @responses = @record.responses
  end

  protected

  def set_study
    @study = Study.find(params[:study_id])
  end

  def record_params
    params.require(:record).permit(:notes)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def index
    @record = Record.find(params[:record_id])
  end

  def new
    @record = Record.find(params[:record_id])
    @participant = Participant.find(params[:participant_id])
    @response = Response.new
  end

  def create
    @record = Record.find(params[:record_id])
    @participant = Participant.find(params[:participant_id])
    response = @record.responses.create(response_params)

    if response.save
      redirect_to success_path
    else
      flash[:notice] = 'There were some errors with saving your answers.'
      redirect_to :back
    end
  end

  protected

  def response_params
    params.require(:response).permit(:pleasure, :purpose, :what, :who, :participant_id)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'static'
  
  def welcome
    if user_signed_in?
      redirect_to studies_path
    end
  end

  def success
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @studies = Study.owned_by(current_user)
  end

  def show
  end

  def new
    @study = Study.new
  end

  def edit
  end

  def create
    @study = current_user.studies.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_study
      @study = Study.find(params[:id])
    end

    def study_params
      params.require(:study).permit(:title, :description, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class='container-fluid' style='background-color: #2E222B;'>
  <% if current_user %><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn' %>
  <%= link_to 'Studies Home', studies_path, class: 'btn' %><% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WellbeingMeasure</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <% unless current_page?(root_path) %>
      <%= render 'layouts/header' %>
  <% end %>


  <main>
  <% if notice %>
    <p id='notice'><%= notice %></p>
  <% end %>
  
    <%= yield %>
  </main>

</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WellbeingMeasure</title>
  <%= stylesheet_link_tag 'static' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/participants/_form.html.erb
<%= form_for [@study, @participant] do |f| %>

  <%= f.label :first_name, 'First Name' %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name, 'Last Name' %>
  <%= f.text_field :last_name %>
  <%= f.label :email, 'Email Address' %>
  <%= f.text_field :email %>
  <%= f.label :phone, 'Phone Number' %>
  <%= f.text_field :phone %>
  <%= f.label :notes, 'Notes' %>
  <%= f.text_area :notes %>

  <div class="actions">
    <%= f.submit "Add Participant" %>
  </div>
<% end %>

app/views/participants/index.html.erb
<h1>Participants in <%= @study.title %></h1>

<% if @study.participants.empty? %>
  <p>There are no participants yet! <%= link_to "Add Participants", new_study_participant_path(@study) %></p>
<% else %>
  <ol>
    <% @study.participants.each do |participant| %>
    <li><%= participant.first_name %> <%= participant.last_name %>, <%= participant.email %>
      <%= link_to 'Remove', study_participant_path(@study, participant), method: :delete %></li>
    <% end %>
  </ol>
<% end %>

app/views/participants/new.html.erb
<p>All participants will receive an email notification that they have been added to this study.</p>

<%= render 'participants/form' %>

app/views/records/index.html.erb
<%= link_to '<< Back', study_path(@study) %>
<h1>Collected Records for <%= @study.title %></h1>

<% if @study.records.empty? %>
  <p>No data collection events have been sent out yet.</p>
<% else %>
  <% @study.records.each do |record| %>
    <li><%= link_to record.created_at, study_record_path(@study, record) %></li>
  <% end %>
<% end %>

app/views/records/new.html.erb
<h1>Creating New Data Collection Event</h1>

<p>For now, the questions sent to participants are standardized.</p>
<p>In the future, you will be able to specify which questions you want to send to participants.</p>

<ol>
  <li>Please rate your sense of pleasure on a scale of 1-10.</li>
  <li>Please rate your sense of purpose on a scale of 1-10.</li>
  <li>What are you doing right now?</li>
  <li>Who are you with?</li>
</ol>

<p>You may include some additional notes to participants in the following field.</p>

<%= form_for [@study, @record] do |f| %>
  <%= f.label :notes, 'Notes' %>
  <%= f.text_area :notes %>
  <div class='actions'>
    <%= f.submit 'Send' %>
  </div>
<% end %>

app/views/records/show.html.erb
<%= link_to '<< Back', :back %>

<h1>Received Responses</h1>

<table>
  <thead>
    <tr>
      <td>Time</td>
      <td>Date</td>
      <td>Participant ID</td>
      <td>With whom?</td>
      <td>Doing what?</td>
      <td>Pleasure Rating</td>
      <td>Purpose Rating</td>
    </tr>
  </thead>
  <tbody>
    <% @responses.each do |response| %>
    <tr>
      <td><%= response.created_at.strftime("%m:%M %p") %></td>
      <td><%= response.created_at.strftime("%e %b %Y") %></td>
      <td><%= response.participant_id %></td>
      <td><%= response.who %></td>
      <td><%= response.what %></td>
      <td><%= response.pleasure %></td>
      <td><%= response.purpose %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/responses/_form.html.erb
<%= form_for [@record, @participant, @response] do |f| %>

  <%= f.label :who, 'Who are you with?' %>
  <%= f.select :who, options_for_select(['Boss', 'Colleagues', 'Alone']) %>
  <%= f.label :what, 'What are you currently doing?' %>
  <%= f.select :what, options_for_select(['Working', 'Taking a break', 'Commuting', 'Meeting', 'Eating', 'Other']) %>
  <%= f.label :pleasure, 'Rate your sense of pleasure.' %>
  <%= f.select :pleasure, options_for_select([*1..10]) %>
  <%= f.label :purpose, 'Rate your sense of purpose.' %>
  <%= f.select :purpose, options_for_select([*1..10]) %>
  <%= f.hidden_field :participant_id, value: @participant.id %>

  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/responses/new.html.erb
<h1>You are logging answers for the following study: <%= @record.study.title %></h1>

<%= render 'form' %>

app/views/studies/_form.html.erb
<%= form_for(@study) do |f| %>
  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title, 'Title' %>
  <%= f.text_field :title %>
  <%= f.label :description, 'Description' %>
  <%= f.text_area :description %>
  <%= f.label :start_date, 'Start Date' %>
  <%= f.text_field :start_date %>
  <%= f.label :end_date, 'End Date' %>
  <%= f.text_field :end_date %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing study</h1>

<%= render 'form' %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<h1>Studies Dashboard</h1>
<p>Manage your existing studies.</p>

<div class='container-fluid studies-container'>
  <div class='row'>
    <div class='col-2 studies-col'>
      <h3>Current Studies</h3>
      <% if @studies.any? %>
      <ol>
        <% @studies.each do |study| %>
        <li><%= link_to study.title, study_path(study) %></li>
        <% end %>
      </ol>
      <% else %>
        <p>You have not created any studies yet!</p>
      <% end %>
    </div>
    <div class='col-2 studies-col'><h3><%= link_to 'Create New Study', new_study_path %></h3></div>
  </div>
</div>

app/views/studies/new.html.erb
<h1>New study</h1>

<%= render 'form' %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<h1>Management Dashboard for <%= @study.title %></h1>
<p><%= link_to 'Edit This Study', edit_study_path(@study) %>
  <%= link_to 'Delete', study_path(@study), method: :delete, data: { confirm: 'Are you sure?' } %></p>
<hr>
<li><%= link_to 'View Participants', study_participants_path(@study) %></li>
<li><%= link_to 'Invite Participants', new_study_participant_path(@study) %></li>
<hr>
<li><%= link_to 'Send Out Survey', new_study_record_path(@study) %></li>
<li><%= link_to 'View Records', study_records_path(@study) %></li>
<li><%= link_to 'Export CSV', study_records_path(@study, format: 'csv') %></li>